name: 🧩 CI · Merge

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pearchha-merge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_swift_build_common.yml@0efa5d3b275e474e54af0ced8ba1a771f6b9df7c
    with:
      ref: ${{ github.sha }}
      dry_run: true
      upload_artifact: true
    secrets: inherit
