name: 🧩 CI · Merge

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: pearchha-merge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_swift_build_common.yml@4bbf9f8a3f6848f08be3e00ab05e39702cd95aaf
    with:
      ref: ${{ github.sha }}
      dry_run: true
      upload_artifact: true
    secrets: inherit
