name: 🧩 CI · Merge

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pearchha-merge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_swift_build_common.yml@b469d48bd53ec336312b5d541e247c16c5fd0f2d
    with:
      ref: ${{ github.sha }}
      dry_run: true
      upload_artifact: true
    secrets: inherit
