# yuna-release: true
name: 🏷️ CD · Release

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force.
        required: true
        default: false
        type: boolean

permissions:
  actions: read
  contents: write

jobs:
  release:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_swift_release.yml@b469d48bd53ec336312b5d541e247c16c5fd0f2d
    with:
      force: ${{ inputs.force }}
    secrets: inherit
